### ISSUE TITLE
moment instances don't have some locale methods of global moment

### ISSUE THREAD

**Issue by freiksenet** [moment/moment#1945]
Seems that localeData objects of moment doesn't get the functions to get list of month names or weekday names, instead it only gets the function that formats one moment instance.

``` javascript
> moment.months()
[ 'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December' ]
> var m = moment();
> m.months()
8
> m.localeData().months()
TypeError: Cannot call method 'month' of undefined
    at Locale.extend.months
    at repl:1:17
    at REPLServer.self.eval (repl.js:110:21)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.emit (events.js:95:17)
    at Interface._onLine (readline.js:202:10)
    at Interface._line (readline.js:531:8)
    at Interface._ttyWrite (readline.js:760:14)
    at ReadStream.onkeypress (readline.js:99:10)
    at ReadStream.emit (events.js:98:17)
```

**Comment by marwahaha** [comment]
See https://momentjs.com/docs/#/-project-status/
