### ISSUE TITLE
date diff error for same date

### ISSUE THREAD

**Issue by hodiapa** [moment/moment#2521]
```javascript
var now = moment().format('YYYY MM DD')
console.log("time is "+ now)
var now1 = moment().format('YYYY MM DD')
console.log("Diff Now:  "+ now.diff(now1, 'days'))
```

Produces the following error

```
console.log("Diff Now:  "+ now.diff(now1, 'days'))
                               ^
TypeError: undefined is not a function
    at Object.<anonymous> (c:\work_folder\trial_apps\\testMoment.js:18:32)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by mj1856** [comment]
`format` returns a string.  `diff` is a function on `moment`.  I believe you want:

```javascript
var now = moment();
console.log("time is "+ now.format('YYYY MM DD'));
var now1 = moment();
console.log("Diff Now: "+ now.diff(now1, 'days'));
```

Though in this particular example, the result will be `0` since both `now` and `now` are run at the same time.
