### ISSUE TITLE
moment crashs if you try to strictly validate locale dates

### ISSUE THREAD

**Issue by iamstarkov** [moment/moment#2527]
```
➜  get-md-date git:(master) npm ls | grep moment
├── moment@2.10.6
➜  get-md-date git:(master) node
> var moment = require('moment');
undefined
> moment('21 декабря 2015', 'DD MMM YYYY', 'ru', true).isValid();
TypeError: Cannot read property '0' of undefined
    at Locale.localeMonthsParse [as monthsParse] (/Users/matmuchrapna/projects/get-md-date/node_modules/moment/moment.js:659:49)
    at Object.<anonymous> (/Users/matmuchrapna/projects/get-md-date/node_modules/moment/moment.js:626:36)
    at addTimeToArrayFromToken (/Users/matmuchrapna/projects/get-md-date/node_modules/moment/moment.js:580:26)
    at configFromStringAndFormat (/Users/matmuchrapna/projects/get-md-date/node_modules/moment/moment.js:1199:17)
    at prepareConfig (/Users/matmuchrapna/projects/get-md-date/node_modules/moment/moment.js:1336:13)
    at createFromConfig (/Users/matmuchrapna/projects/get-md-date/node_modules/moment/moment.js:1307:44)
    at createLocalOrUTC (/Users/matmuchrapna/projects/get-md-date/node_modules/moment/moment.js:1385:16)
    at local__createLocal (/Users/matmuchrapna/projects/get-md-date/node_modules/moment/moment.js:1389:16)
    at utils_hooks__hooks (/Users/matmuchrapna/projects/get-md-date/node_modules/moment/moment.js:16:29)
    at repl:1:1
```

prob I missed something, so ask me anything

**Comment by mj1856** [comment]
Yes, this has been discovered already.

See #2243 & #2493

**Comment by iamstarkov** [comment]
suggesting "duplicate" label for this kind of issues

**Comment by iamstarkov** [comment]
anyway, thank you for answer. will continue in those issues

**Comment by iamstarkov** [comment]
@Viktorminator, @Oire hi, can I ask to take a look at this issue? I tried to fix it, but failed. Can you help me?

**Comment by Oire** [comment]
@iamstarkov, sorry for such a late reply. Wait a bit please, I'll be on it in several days. Аврал на работе такой, что жуть. Надеюсь к выходным сюда приплыть и спокойно рассмотреть все инциденты с локалями :)

**Comment by iamstarkov** [comment]
Thanks Спасибо

**Comment by iamstarkov** [comment]
@mj1856 can i ask you to re-open this issue? after investigation I found that relating issues are not about russian locale, thank you

**Comment by mj1856** [comment]
In #2243:

> Ok, this is problem is pretty serious and touches `sk`, `cs` and `ru` locales.

#2493 fixes for `sk` and `cs`.  So we just need a separate fix for `ru`.

**Comment by iamstarkov** [comment]
@Oire any news here?

**Comment by iamstarkov** [comment]
@Oire привет. можешь посмотреть пожалуйста ещё раз?

**Comment by ichernev** [comment]
Have a look at #2634.

It is a duplicate.

**Comment by iamstarkov** [comment]
ok, will follow #2634
