### ISSUE TITLE
moment object to duration is deprecated/broken

### ISSUE THREAD

**Issue by StevenRKM** [moment/moment#3440]
**Description of the Issue and Steps to Reproduce:**

Converting a moment object to a duration used to work properly.

`moment.duration(moment())`

Currently it gives this warning:

`Deprecation warning: value provided is not in a recognized ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: function from(time, withoutSuffix) {
        if (this.isValid() &&
                ((isMoment(time) && time.isValid()) ||
                 local__createLocal(time).isValid())) {
            return create__createDuration({to: this, from: time}).locale(this.locale()).humanize(!withoutSuffix);
        } else {
            return this.localeData().invalidDate();
        }
    }, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (http://momentjs.com/static/js/global.js:309:98)
    at configFromInput (http://momentjs.com/static/js/global.js:2420:32)
    at prepareConfig (http://momentjs.com/static/js/global.js:2391:13)
    at createFromConfig (http://momentjs.com/static/js/global.js:2358:44)
    at createLocalOrUTC (http://momentjs.com/static/js/global.js:2445:16)
    at local__createLocal (http://momentjs.com/static/js/global.js:2449:16)
    at Function.create__createDuration [as duration] (http://momentjs.com/static/js/global.js:2825:41)
    at <anonymous>:1:8`

And the output is a duration that is set to 0, so it is broken.

I found the point where it changed, between 2.11.1 and 2.11.2
JSFiddle
(broken) moment v2.15.0: https://jsfiddle.net/StevenRKM/p10aups2/ 
(broken) moment v2.11.2: https://jsfiddle.net/StevenRKM/8xkupx40/1/
(working) moment v.2.11.1: https://jsfiddle.net/StevenRKM/2evm9o8c/

**Environment:**

Checked in latest Chrome with latest and previous moment versions.
Working on Windows 7.

**Comment by icambron** [comment]
Hmm, I'm not sure that was ever supported: http://momentjs.com/docs/#/durations/creating/. It may be the case that passing in a moment happened to have worked (not sure what it means, actually -- a duration equal to the number of milliseconds since 1970 in the moment object?) and now it doesn't. Can you point me to where you derived that expectation? Just from trying it?

There is a minor bug here in that the deprecation warning is being printed for the wrong case (it's meant for a string input).

**Comment by icambron** [comment]
After thinking about this a bit, I've decided to close it as won't-fix. The deprecation warning isn't quite right and I can see how it confused things here, but it's a little annoying to fix and will be going away soon anyway.

**Comment by tejastank** [comment]
We getting this same.

Deprecation warning: value provided is not in a recognized ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 27/04/2016, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (http://example.local/ib-admin/static/libs/moment-with-locales.js:309:98)
    at configFromString (http://example.local/ib-admin/static/libs/moment-with-locales.js:2048:32)
    at configFromInput (http://example.local/ib-admin/static/libs/moment-with-locales.js:2408:13)
    at prepareConfig (http://example.local/ib-admin/static/libs/moment-with-locales.js:2391:13)
    at createFromConfig (http://example.local/ib-admin/static/libs/moment-with-locales.js:2358:44)
    at createLocalOrUTC (http://example.local/ib-admin/static/libs/moment-with-locales.js:2445:16)
    at local__createLocal (http://example.local/ib-admin/static/libs/moment-with-locales.js:2449:16)
    at utils_hooks__hooks (http://example.local/ib-admin/static/libs/moment-with-locales.js:16:29)
    at http://example.local/ib-admin/static/js/form.js:570:52
    at Function.m.each.m.forEach (http://example.local/ib-admin/static/libs/underscore-min.js:5:2410)

**Comment by butterflyhug** [comment]
@tejastank - It looks like you created a moment from the string "27/04/2016", without any Durations involved.  That is exactly the sort of use case that the deprecation warning is intended for.  Take a look at the linked page for more info:  http://momentjs.com/guides/#/warnings/js-date/

**Comment by pablougas** [comment]
I'm getting a kicked back error on this as well. I get the initial fire just fine but then when partial is refreshed via ajax and I run the function again to replace the utc times, then I get the following error. 

```moment.self-0da3eb4….js?body=1:282 Deprecation warning: value provided is not in a recognized ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: true, _useUTC: true, _l: undefined, _i: 9:30 AM, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (http://localhost:3000/assets/moment.self-0da3eb4ebf8fb8c3113d89afb90e5b7a87760d21b5b39a405a51fe05c8e40fd8.js?body=1:309:98)
    at configFromString (http://localhost:3000/assets/moment.self-0da3eb4ebf8fb8c3113d89afb90e5b7a87760d21b5b39a405a51fe05c8e40fd8.js?body=1:2048:32)
    at configFromInput (http://localhost:3000/assets/moment.self-0da3eb4ebf8fb8c3113d89afb90e5b7a87760d21b5b39a405a51fe05c8e40fd8.js?body=1:2408:13)
    at prepareConfig (http://localhost:3000/assets/moment.self-0da3eb4ebf8fb8c3113d89afb90e5b7a87760d21b5b39a405a51fe05c8e40fd8.js?body=1:2391:13)
    at createFromConfig (http://localhost:3000/assets/moment.self-0da3eb4ebf8fb8c3113d89afb90e5b7a87760d21b5b39a405a51fe05c8e40fd8.js?body=1:2358:44)
    at createLocalOrUTC (http://localhost:3000/assets/moment.self-0da3eb4ebf8fb8c3113d89afb90e5b7a87760d21b5b39a405a51fe05c8e40fd8.js?body=1:2445:16)
    at Function.create_utc__createUTC [as utc] (http://localhost:3000/assets/moment.self-0da3eb4ebf8fb8c3113d89afb90e5b7a87760d21b5b39a405a51fe05c8e40fd8.js?body=1:79:16)
    at HTMLSpanElement.<anonymous> (http://localhost:3000/assets/property_managers.self-895a4d0a7996e8f93b9ea36ae034c3647d712d2079b1c33fdcb3931fee02e492.js?body=1:41:66)
    at Function.each (http://localhost:3000/assets/jquery.self-bd7ddd393353a8d2480a622e80342adf488fb6006d667e8b42e4c0073393abee.js?body=1:371:19)
    at jQuery.fn.init.each (http://localhost:3000/assets/jquery.self-bd7ddd393353a8d2480a622e80342adf488fb6006d667e8b42e4c0073393abee.js?body=1:138:17)```
