### ISSUE TITLE
Contributor Guidance - Setting up development environment

### ISSUE THREAD

**Issue by TracyGJG** [moment/moment#3826]
**Issue:**
The procedure given in the guidance is either missing a step or prerequisite actions. I followed the instructions precisely but was presented with an incomplete build. 

I have tried referencing ```node_modules``` in my path environment variable but it does not resolve the issue.

**Environment:**
Windows 10 Pro, Node 7.5, NPM 4.1.2,

**Output provided:**
```
Deprecation warning: testing deprecation
Arguments:
Error
    at C:\Users\tracy\Documents\Aptana Studio 3 Workspace\moment\build\umd\test\moment\deprecate.js:346:98
    at Object.<anonymous> (C:\Users\tracy\Documents\Aptana Studio 3 Workspace\moment\build\umd\test\moment\deprecate.js:375:9)
    at Test.run (C:\Users\tracy\Documents\Aptana Studio 3 Workspace\moment\node_modules\qunitjs\qunit\qunit.js:136:18)
    at C:\Users\tracy\Documents\Aptana Studio 3 Workspace\moment\node_modules\qunitjs\qunit\qunit.js:279:10
    at process (C:\Users\tracy\Documents\Aptana Studio 3 Workspace\moment\node_modules\qunitjs\qunit\qunit.js:1277:24)
    at Timeout._onTimeout (C:\Users\tracy\Documents\Aptana Studio 3 Workspace\moment\node_modules\qunitjs\qunit\qunit.js:383:5)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)


Errors:

Module: relative time Test: custom rounding
Round down towards the nearest day
    at Object.<anonymous> (C:\Users\tracy\Documents\Aptana Studio 3 Workspace\moment\build\umd\test\moment\relative_time.js:438:16)
    at Test.run (C:\Users\tracy\Documents\Aptana Studio 3 Workspace\moment\node_modules\qunitjs\qunit\qunit.js:136:18)
    at C:\Users\tracy\Documents\Aptana Studio 3 Workspace\moment\node_modules\qunitjs\qunit\qunit.js:279:10
    at process (C:\Users\tracy\Documents\Aptana Studio 3 Workspace\moment\node_modules\qunitjs\qunit\qunit.js:1277:24)
    at Timeout._onTimeout (C:\Users\tracy\Documents\Aptana Studio 3 Workspace\moment\node_modules\qunitjs\qunit\qunit.js:383:5)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
Actual value:
in a month
Expected value:
in 30 days

Global summary:
+--------------------------------------------------------+
¦ Files ¦ Tests ¦ Assertions ¦ Failed ¦ Passed ¦ Runtime ¦
+-------+-------+------------+--------+--------+---------¦
¦ 1     ¦ 2781  ¦ 114093     ¦ 1      ¦ 114092 ¦ 18405   ¦
+--------------------------------------------------------+
Warning: 1 tests failed Used --force, continuing.

Running "exec:typescript-test" (exec) task
>> 'node_modules' is not recognized as an internal or external command,
>> operable program or batch file.
>> Exited with code: 1.
>> Error executing child process: Error: Command failed: node_modules/.bin/tsc --project typing-tests
>> 'node_modules' is not recognized as an internal or external command,
>> operable program or batch file.
Warning: Task "exec:typescript-test" failed. Used --force, continuing.
```

**Comment by icambron** [comment]
Yeah, it looks to me like there's a section of the build file that assumes Unix paths:

```js
            'typescript-test': {
                command: 'node_modules/.bin/tsc --project typing-tests'
           }
```

I haven't developed on Windows in a long time, so I'm not sure what the best way to fix that is. @mj1856 any ideas there?

In the meantime, here's a workaround:

 1. Open Gruntfile.js
 2. Find this line: `grunt.registerTask('test', ['test:node', 'test:typescript']);`
 3. Remove the second item in the array (meaning, don't run the Typescript tests as part of the test suite)

In addition to that, make sure you're on the latest version of the `develop` branch. The one test failure you have is almost certainly the one fixed [here](https://github.com/moment/moment/pull/3799), which suggests that you're not quite up to date.

**Comment by TracyGJG** [comment]
Thanks for the advice. I have found an alternative workaround that does not require a change to Gruntfile.js. Instead of running the default grunt command I use:

```
grunt lint test:node
```

**Comment by icambron** [comment]
Yeah, that makes sense.

I'm going to reopen this issue though. We should fix this.

**Comment by marwahaha** [comment]
This might be simple.

@TracyGJG , could you check if this works? Change the offending line to:
```
                command: './node_modules/.bin/tsc --project typing-tests'
```
and run `grunt`.

**Comment by TracyGJG** [comment]
Command Prompt

**Comment by TracyGJG** [comment]
Good call. It works fine for me now.

```
Running "exec:typescript-test" (exec) task

> moment@2.17.1 typescript-test C:\Users\xxxx\moment
> tsc --project typing-tests


Done, without errors.
```

**Comment by maggiepint** [comment]
closing, #3840
