### ISSUE TITLE
Force deprecation warnings into real errors, not console logs

### ISSUE THREAD

**Issue by GeoffreyPlitt** [moment/moment#4345]
Hi,

We're seeing console logs like this from time to time, but we can't trap this condition to print the input that caused it. Instead of console.logging, is there a way to force moment to throw an error in this case?

```
Dec 07 16:00:53 stardust-backend app/web.1:  Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info. 
Dec 07 16:00:53 stardust-backend app/web.1:  Arguments:  
Dec 07 16:00:53 stardust-backend app/web.1:  [0] _isAMomentObject: true, _isUTC: true, _useUTC: true, _l: undefined, _i: 3caf6199-9d10-4023-a032-1fc8dcd368d7, _f: undefined, _strict: undefined, _locale: [object Object] 
Dec 07 16:00:53 stardust-backend app/web.1:  Error 
Dec 07 16:00:53 stardust-backend app/web.1:      at Function.createFromInputFallback (/app/node_modules/moment/moment.js:324:94) 
Dec 07 16:00:53 stardust-backend app/web.1:      at configFromString (/app/node_modules/moment/moment.js:2364:11) 
Dec 07 16:00:53 stardust-backend app/web.1:      at configFromInput (/app/node_modules/moment/moment.js:2590:9) 
Dec 07 16:00:53 stardust-backend app/web.1:      at prepareConfig (/app/node_modules/moment/moment.js:2573:9) 
Dec 07 16:00:53 stardust-backend app/web.1:      at createFromConfig (/app/node_modules/moment/moment.js:2540:40) 
Dec 07 16:00:53 stardust-backend app/web.1:      at createLocalOrUTC (/app/node_modules/moment/moment.js:2627:12) 
Dec 07 16:00:53 stardust-backend app/web.1:      at Function.createUTC [as utc] (/app/node_modules/moment/moment.js:92:12) 
Dec 07 16:00:53 stardust-backend app/web.1:      at big_helper (/app/util/home_grid_get_paged_reactions_v2.js:44:24) 
Dec 07 16:00:53 stardust-backend app/web.1:      at Object.main (/app/util/home_grid_get_paged_reactions_v2.js:122:5) 
Dec 07 16:00:53 stardust-backend app/web.1:      at router.route.post (/app/api/reactions.js:44:36) 
Dec 07 16:00:53 stardust-backend app/web.1:      at Layer.handle (/app/node_modules/express/lib/router/layer.js:95:5) 
Dec 07 16:00:53 stardust-backend app/web.1:      at Layer.wrapped (/app/node_modules/newrelic/lib/transaction/tracer/index.js:184:28) 
Dec 07 16:00:53 stardust-backend app/web.1:      at Layer.wrappedLayerHandleRequest [as handle_request] (/app/node_modules/newrelic/lib/instrumentation/express.js:364:14) 
Dec 07 16:00:53 stardust-backend app/web.1:      at next (/app/node_modules/express/lib/router/route.js:137:13) 
Dec 07 16:00:53 stardust-backend app/web.1:      at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3) 
Dec 07 16:00:53 stardust-backend app/web.1:      at Layer.wrappedHandle (/app/node_modules/newrelic/lib/instrumentation/express.js:597:19) 
Dec 07 16:00:53 stardust-backend app/web.1:      at dispatch (eval at wrapHandle (/app/node_modules/newrelic/lib/instrumentation/express.js:440:19), <anonymous>:4:28) 
Dec 07 16:00:53 stardust-backend app/web.1:      at Layer.handle (/app/node_modules/express/lib/router/layer.js:95:5) 
Dec 07 16:00:53 stardust-backend app/web.1:      at Layer.wrapped (/app/node_modules/newrelic/lib/transaction/tracer/index.js:184:28) 
Dec 07 16:00:53 stardust-backend app/web.1:      at Layer.wrappedLayerHandleRequest [as handle_request] (/app/node_modules/newrelic/lib/instrumentation/express.js:364:14) 
Dec 07 16:00:53 stardust-backend app/web.1:      at /app/node_modules/express/lib/router/index.js:281:22 
Dec 07 16:00:53 stardust-backend app/web.1:      at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12) 
```

**Comment by marwahaha** [comment]
Perhaps there could be a flag that turns deprecation logs into real errors.

**Comment by ichernev** [comment]
You can overwrite `moment.createFromInputFallback` and throw as many exceptions as you want in it :)

I think we're doing enough on the moment side.
