### ISSUE TITLE
Creating dodgy dates should fail, probably with an error

### ISSUE THREAD

**Issue by RobinKnipe** [moment/moment#4419]
The REPL extract below shows the problem:

```js
// date entered in reverse format
> var d = mo('2016-01-30', 'DD-MM-YYYY')
undefined
> d
moment("2030-01-20T00:00:00.000")
> d.isValid()
true
// bonkers date format, and date entered in reverse format
> d = mo('2016-01-30', 'dd-mm-yyyy')
undefined
> d
moment("2018-01-29T00:01:00.000")
> d.isValid()
true
```

Rather than the moment constructor refusing a date format that clearly doesn't matching the desired format (which I'm suggesting should be the expected behaviour), it simply returns a best guess or today's date instead! This is dangerous because there's no indication that the input date was dodgy.

**Environment:**
node.js
```js
> console.log( (new Date()).toString())
Mon Jan 29 2018 14:15:15 GMT+0000 (GMT)
undefined
> console.log((new Date()).toLocaleString())
2018-1-29 14:15:15
undefined
> console.log( (new Date()).getTimezoneOffset())
0
undefined
> console.log( navigator.userAgent)
ReferenceError: navigator is not defined
    at repl:1:14
    at ContextifyScript.Script.runInThisContext (vm.js:44:33)
    at REPLServer.defaultEval (repl.js:239:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:433:10)
    at emitOne (events.js:120:20)
    at REPLServer.emit (events.js:210:7)
    at REPLServer.Interface._onLine (readline.js:278:10)
    at REPLServer.Interface._line (readline.js:625:8)
> console.log(moment.version)
2.19.2
```

**Comment by ashsearle** [comment]
Use [strict mode](https://momentjs.com/guides/#/parsing/strict-mode/)

```
> d = mo('2016-01-30', 'DD-MM-YYYY', true)
moment.invalid(/* 2016-01-30 */)
> d.isValid()
false
> d = mo('2016-01-30', 'dd-mm-yyyy', true)
moment.invalid(/* 2016-01-30 */)
> d.isValid()
false
```

**Comment by RobinKnipe** [comment]
Ah yes, I think that'll suffice. Thanks @ashsearle !
