### ISSUE TITLE
Deprecated message on Chrome

### ISSUE THREAD

**Issue by vbbalaji** [moment/moment#4565]
**Description of the Issue and Steps to Reproduce:**
Im converting a date string to moment date and get the month value using moment(dateStr).month. Im getting the below error message.

moment.js:297 Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: NULL, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (http://localhost/cust-bs4/js/moment.js:324:94)
    at configFromString (http://localhost/cust-bs4/js/moment.js:2366:11)
    at configFromInput (http://localhost/cust-bs4/js/moment.js:2592:9)
    at prepareConfig (http://localhost/cust-bs4/js/moment.js:2575:9)
    at createFromConfig (http://localhost/cust-bs4/js/moment.js:2542:40)
    at createLocalOrUTC (http://localhost/cust-bs4/js/moment.js:2629:12)
    at createLocal (http://localhost/cust-bs4/js/moment.js:2633:12)
    at hooks (http://localhost/cust-bs4/js/moment.js:16:25)
    at Object.<anonymous> (http://localhost/cust-bs4/landing.html:1685:42)
    at Function.each (http://localhost/cust-bs4/js/jquery-3.3.1.min.js:2:2573)

*Please include the values of all variables used.*
tEvent.reportMonth = moment(tEvent.actstartdt).month();

**Environment:**
Version 65.0.3325.181 (Official Build) (64-bit) on Windows 10.

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on : EST
* The time and date at which the code was run : 4/16/18 10:30am
* Other libraries in use (TypeScript, Immutable.js, etc)
jquery-3.3.1.min.js
bootstrap.js
base.js
underscore.js
moment.js
moment-timezone-with-data.js
lodash.js
jquery.easypiechart.js

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)
```
Mon Apr 16 2018 10:44:36 GMT-0400 (Eastern Daylight Time)
4/16/2018, 10:44:36 AM
240
Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A372 Safari/604.1
2.20.1

*Ensure your issue is isolated to moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

**Comment by ashsearle** [comment]
Can you gives us an example value for `tEvent.actstartdt` being used in

```jst
Event.reportMonth = moment(tEvent.actstartdt).month();
```

Where does that value come from?  Is there a reason it isn't or can't be provided in a format matching one of the standards mentioned? (ISO8901 or RFC2822)?

**Comment by vbbalaji** [comment]
Found it! The DB service was sending null value in a quoted string. So the above function was trying to convert "NULL" into a date. I did have a check to handle null and "" but not this. 
However, my question is why would it give a deprecated warning?

**Comment by ashsearle** [comment]
As is says in the warning:
> moment construction falls back to js Date(), which is not reliable across all browsers and versions

Unreliable means unpredictable, so deprecated.
