### ISSUE TITLE
Crash on simple date

### ISSUE THREAD

**Issue by myster-t** [moment/moment#4764]
**Description of the Issue and Steps to Reproduce:**
Parse a simple date like 'Sept 4, 2018' with moment will cause a crash. What am I doing wrong?

Same thing happens with any simple dates pass directly to `moment`. The fallback to `Date` doesn't seem to work. Wrapping a `Date` also doesn't work for same string. However, simply parsing string with `Date` does work.

**Environment:**
node v8.11.3, running moment v2.22.2, amazon linux ami release 2018.03

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
> var moment = require('moment')
> var out = moment('Sept 4, 2018')
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments:
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: Sept 4, 2018, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (/opt/whiskers/whiskers/node_modules/moment/moment.js:320:98)
    at configFromString (/opt/whiskers/whiskers/node_modules/moment/moment.js:2368:15)
    at configFromInput (/opt/whiskers/whiskers/node_modules/moment/moment.js:2594:13)
    at prepareConfig (/opt/whiskers/whiskers/node_modules/moment/moment.js:2577:13)
    at createFromConfig (/opt/whiskers/whiskers/node_modules/moment/moment.js:2544:44)
    at createLocalOrUTC (/opt/whiskers/whiskers/node_modules/moment/moment.js:2631:16)
    at createLocal (/opt/whiskers/whiskers/node_modules/moment/moment.js:2635:16)
    at hooks (/opt/whiskers/whiskers/node_modules/moment/moment.js:12:29)
    at repl:1:11
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
> var out = Date('Sept 4, 2018')
> out
'Tue Sep 04 2018 18:44:12 GMT+0000 (UTC)'


> var out = moment(Date('Sept 4, 2018'))
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments:
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: Tue Sep 04 2018 18:49:34 GMT+0000 (UTC), _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (/opt/whiskers/whiskers/node_modules/moment/moment.js:320:98)
    at configFromString (/opt/whiskers/whiskers/node_modules/moment/moment.js:2368:15)
    at configFromInput (/opt/whiskers/whiskers/node_modules/moment/moment.js:2594:13)
    at prepareConfig (/opt/whiskers/whiskers/node_modules/moment/moment.js:2577:13)
    at createFromConfig (/opt/whiskers/whiskers/node_modules/moment/moment.js:2544:44)
    at createLocalOrUTC (/opt/whiskers/whiskers/node_modules/moment/moment.js:2631:16)
    at createLocal (/opt/whiskers/whiskers/node_modules/moment/moment.js:2635:16)
    at hooks (/opt/whiskers/whiskers/node_modules/moment/moment.js:12:29)
    at repl:1:11
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
```

However, moment is otherwise working fine:

```js
> moment()
moment("2018-09-04T18:59:18.875")
> var out = moment([2010, 1, 14, 15, 25, 50, 125]);
> out
moment("2010-02-14T15:25:50.125")
```

Moment can be forced to parse the date if the correct format is passed, but we can't predict the format in our system:

```js
> var out = moment('Sept 4, 2018', 'MMM D, YYYY')
> out
moment("2018-09-04T00:00:00.000")
```

**Comment by ashsearle** [comment]
You're not doing anything wrong.

moment is _warning_ you that you're parsing a date in a non-standard format, without telling it what format it is.

It's telling you that the result is going to be unreliable and inconsistent across browsers / runtimes.

I guess my question would be: why can't you predict the format in your system?  Where are the dates coming from: user-input, or ...?

**Comment by myster-t** [comment]
Why is it giving me the same warning when i'm wrapping a `Date` object? Shouldn't that be agnostic to the string I created the `Date` object with?

I can't predict the format because some of the data is user inputed and some are from various data sources -- all external data sources and all varied formats. My hope was to utilize `moment` to have one workflow for understanding the date value, without trying to guess at the format with regex or otherwise.

**Comment by ashsearle** [comment]
Do you mean this code?
```
> var out = moment(Date('Sept 4, 2018'))
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
```

That code isn't 'wrapping a `Date` object', it's calling `Date` as a function instead of a constructor, which returns a `String`.  You show this yourself, a few lines up:

```
> var out = Date('Sept 4, 2018')
> out
'Tue Sep 04 2018 18:44:12 GMT+0000 (UTC)'
```

So, `moment(Date('Sept 4, 2018'))` is (for you) the same as calling `moment('Tue Sep 04 2018 18:44:12 GMT+0000 (UTC)')`

**Comment by marwahaha** [comment]
Let us know if you still have troubles. Ash is right, that's a warning, not an error.
