### ISSUE TITLE
Trying to contribute: grunt test, deprecation is failing

### ISSUE THREAD

**Issue by MichaelDimmitt** [moment/moment#5163]
**Describe the bug**
When trying to contribute `grunt test` or `npm test` testing deprecation is failing.

Am I missing a step in Contributions.md?
Maybe Qunit or Grunt is failing after upgrading to a newer version.

**To Reproduce**
1. clone the project
2. git checkout develop
3. npm install
4. npm install -g grunt
5. grunt test
```
grunt --version
grunt-cli v1.3.2
grunt v0.4.5
```

**Expected behavior**
All tests passing

**Actual behavior**
```bash
Running "qtest" task
Deprecation warning: testing deprecation
Arguments: 
Error
    at /Users/michaeldimmitt/moment/build/umd/test/moment/deprecate.js:150:98
    at Object.<anonymous> (/Users/michaeldimmitt/moment/build/umd/test/moment/deprecate.js:167:9)
    at runTest (/Users/michaeldimmitt/moment/node_modules/qunitjs/qunit/qunit.js:1054:30)
    at Test.run (/Users/michaeldimmitt/moment/node_modules/qunitjs/qunit/qunit.js:1040:6)
    at /Users/michaeldimmitt/moment/node_modules/qunitjs/qunit/qunit.js:1214:12
    at process (/Users/michaeldimmitt/moment/node_modules/qunitjs/qunit/qunit.js:2271:26)
    at begin (/Users/michaeldimmitt/moment/node_modules/qunitjs/qunit/qunit.js:2254:4)
    at Timeout._onTimeout (/Users/michaeldimmitt/moment/node_modules/qunitjs/qunit/qunit.js:2215:6)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
Locale return-this not found. Did you forget to load it?
Locale dow:3,doy:6 not found. Did you forget to load it?

Global summary:
┌───────┬───────┬────────────┬────────┬────────┬─────────┐
│ Files │ Tests │ Assertions │ Failed │ Passed │ Runtime │
├───────┼───────┼────────────┼────────┼────────┼─────────┤
│ 1     │ 3609  │ 139691     │ 0      │ 139691 │ 10433   │
└───────┴───────┴────────────┴────────┴────────┴─────────┘

Running "exec:typescript-test" (exec) task

> moment@2.24.0 typescript-test /Users/michaeldimmitt/moment
> tsc --project typing-tests
```

**Desktop (please complete the following information):**
 - OS: MacOS Mohave
 - terminal

**Additional context**

**Comment by MichaelDimmitt** [comment]
possibly related to #4385

However, this is on the develop branch with no changes to the code.

**Comment by ashsearle** [comment]
@MichaelDimmitt All tests are passing (check the Global Summary table)

I find that console.warn output distracting too, but it's not an error.
