### ISSUE TITLE
composer.json update

### ISSUE THREAD

**Issue by xclntdesign** [moment/moment#5391]
Package robloach/component-installer is abandoned. It is suggested switching to oomphinc/composer-installers-extender.

**Comment by vietduc01100001** [comment]
Hi, I'm new to contributing to open-source projects. I replaced the package `robloach/component-installer` with `oomphinc/composer-installers-extender` in `composer.json` file and ran tests with `grunt`. The global summary table showed no failed tests but there was an error when running "qtest".

```
Running "qtest" task
Deprecation warning: testing deprecation
Arguments: 
Error
    at /Users/vietduc/playground/contribute/moment/build/umd/test/moment/deprecate.js:174:25
    at Object.<anonymous> (/Users/vietduc/playground/contribute/moment/build/umd/test/moment/deprecate.js:192:9)
    at runTest (/Users/vietduc/playground/contribute/moment/node_modules/qunitjs/qunit/qunit.js:1054:30)
    at Test.run (/Users/vietduc/playground/contribute/moment/node_modules/qunitjs/qunit/qunit.js:1040:6)
    at /Users/vietduc/playground/contribute/moment/node_modules/qunitjs/qunit/qunit.js:1214:12
    at process (/Users/vietduc/playground/contribute/moment/node_modules/qunitjs/qunit/qunit.js:2271:26)
    at begin (/Users/vietduc/playground/contribute/moment/node_modules/qunitjs/qunit/qunit.js:2254:4)
    at Timeout._onTimeout (/Users/vietduc/playground/contribute/moment/node_modules/qunitjs/qunit/qunit.js:2215:6)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

Is it normal? What did I do wrong?

**Comment by marwahaha** [comment]
I think that's normal. Did the whole thing finish? @vietduc01100001

**Comment by vietduc01100001** [comment]
![image](https://user-images.githubusercontent.com/33684291/82436101-7cb6b080-9abf-11ea-8d11-531285cb3fd8.png)
Here's the global summary. `grunt` succeeded.

**Comment by marwahaha** [comment]
Looks good. Please submit a PR @vietduc01100001
