### ISSUE TITLE
String + Format Constructor still gives Deprecation Warning

### ISSUE THREAD

**Issue by tcvmdev** [moment/moment#5420]
**Describe the bug**
Receive RFC2822 and ISO format deprecation warning, even when passing in String + Format into the constructor

**To Reproduce**
1. Type in the following code:
```
var dateString = moment('03/22/2020')
console.log(moment(dateString, 'MM-DD-YYYY'))
```
2. Run the code using node
3. Receive deprecation warning as follows:
```
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 03/22/2020, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (/Users/jeremychu/Workspace/moment-test/node_modules/moment/moment.js:320:98)
    at configFromString (/Users/jeremychu/Workspace/moment-test/node_modules/moment/moment.js:2385:15)
    at configFromInput (/Users/jeremychu/Workspace/moment-test/node_modules/moment/moment.js:2611:13)
    at prepareConfig (/Users/jeremychu/Workspace/moment-test/node_modules/moment/moment.js:2594:13)
    at createFromConfig (/Users/jeremychu/Workspace/moment-test/node_modules/moment/moment.js:2561:44)
    at createLocalOrUTC (/Users/jeremychu/Workspace/moment-test/node_modules/moment/moment.js:2648:16)
    at createLocal (/Users/jeremychu/Workspace/moment-test/node_modules/moment/moment.js:2652:16)
    at hooks (/Users/jeremychu/Workspace/moment-test/node_modules/moment/moment.js:12:29)
    at Object.<anonymous> (/Users/jeremychu/Workspace/moment-test/index.js:26:18)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
2020-03-22
```

**Expected behavior**
No deprecation warning when string and format are passed into the moment constructor

**Desktop (please complete the following information):**
 - OS: **iOS**
 - Browser: **N/A (running on VS Code Terminal)**
 - Version **10.15.1**

**Moment-specific environment**

* The time zone setting of the machine the code is running on: **EST**
* The time and date at which the code was run: **9:10AM 03/26/2020**
* Other libraries in use: **nodemon babel-cli babel-plugin-transform-object-rest-spread babel-preset-env**

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent) *not included in below output, navigator undefined*
console.log(moment.version)
```
```
Thu Mar 26 2020 09:14:14 GMT-0400 (Eastern Daylight Time)
3/26/2020, 9:14:14 AM
240
2.24.0
```

**Comment by ashsearle** [comment]
The first line is the problem, where you don't pass a format:

```js
var dateString = moment('03/22/2020');
```

**Comment by marwahaha** [comment]
Please re-open if you still have issues.
