### ISSUE TITLE
Syntax error trying to compile an Ember app since 2.25.0

### ISSUE THREAD

**Issue by yemartin** [moment/moment#5576]
**Describe the bug**
Since 2.25.0, our assets compilation pipeline breaks when packaging assets for production.
2.26.0 does not work either.

Reverting to 2.24.0 fixes the issue.

**To Reproduce**
Being a legacy Rails + Ember app, is hard to isolate the issue in a sandbox, but with our code base:

1. Lock moment to version 2.25.0 or 2.26.0
2. `bundle exec rake assets:precompile`

```
Build failed.
File: assets/vendor.js (75284)
Unexpected token: eof (undefined)
SyntaxError: Unexpected token: eof (undefined)
  at JS_Parse_Error.get (<anonymous>:86:23)
  at writeError (/Users/.../ember/node_modules/ember-cli/lib/ui/write-error.js:23:23)
  at UI.writeError (/Users/.../ember/node_modules/ember-cli/lib/ui/index.js:158:3)
  at CLI.logError (/Users/.../ember/node_modules/ember-cli/lib/cli/cli.js:168:11)
  at tryCatch (/Users/.../ember/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:525:12)
  at invokeCallback (/Users/.../ember/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:538:13)
  at publish (/Users/.../ember/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:508:7)
  at publishRejection (/Users/.../ember/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:443:3)
  at flush (/Users/.../ember/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:2415:5)
  at _combinedTickCallback (internal/process/next_tick.js:73:7)
  at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Expected behavior**
With 2.24.0:
```
Built project successfully
```

**Additional context**
Not sure what is most relevant here, but we are using:
- ember-cli@2.3.0
- ember-moment@7.7.0
- uglify-js@2.8.29
- ember-cli-rails gem (0.10.0)

**Comment by marwahaha** [comment]
Sorry you are experiencing an issue.
Can you ensure 2.25.3 or 2.26.0 do not fix your issue?

**Comment by marwahaha** [comment]
This seems to be related to an app called "rsvp"?

**Comment by yemartin** [comment]
About [RSVP](http://inch-ci.org/github/tildeio/rsvp.js), it is a tiny implementation of Promises used by Ember.js. But I don't think it is relevant: I believe RSVP is used as a tool in the assets compilation. But the source of the issue is that, after bundling up all JS code in `assets/vendor.js`, the assets compilation then needs to parse that JS file (in order to minify / uglify it I presume). This is where the SyntaxError occurs. RSVP just happens to be handling the assets compilation process. 

Anyway, I will check more versions and write back.

**Comment by yemartin** [comment]
I checked 2 versions before, and all versions after 2.24.0:

- 2.22.2: ok
- 2.23.0: ok
- 2.24.0: ok
- 2.25.0: SyntaxError
- 2.25.1: SyntaxError
- 2.25.2: SyntaxError
- 2.25.3: SyntaxError
- 2.26.0: SyntaxError

**Comment by marwahaha** [comment]
@yemartin Sorry you are having an issue. It may be better to resolve on StackOverflow.

Perhaps this may help: https://stackoverflow.com/questions/13634049/uglify-js-error-unexpected-token-eof-undefined

You could also look at the diff from 2.24.0 to 2.25.0 .
