### ISSUE TITLE
Module not found: Error: Can't resolve './locale' in '..\node_modules\moment\src\lib\locale'

### ISSUE THREAD

**Issue by jcompagner** [moment/moment#5817]
i know there are a few bug reports for this already and i think it was fixed before but then rollbacked..

because this:
https://github.com/moment/moment/blame/226799e1f8767a8ab2849ea04f595dc82ce83747/src/lib/locale/locales.js#L79
was added and then rollbacked again because now it is this:
https://github.com/moment/moment/blame/develop/src/lib/locale/locales.js#L78

and that require from the standpoint of that file is not correct
from "src/lib/locale/locales.js"

the "./locale/" + name 

is not there (i guess only "en") 
so i get this:

Warning: ./node_modules/moment/src/lib/locale/locales.js
Module not found: Error: Can't resolve './locale' in 'C:\Users\jcomp\git\servoy_master\servoy-eclipse\com.servoy.eclipse.ngclient.ui\node\node_modules\moment\src\lib\locale'
resolve './locale' in 'C:\Users\jcomp\git\servoy_master\servoy-eclipse\com.servoy.eclipse.ngclient.ui\node\node_modules\moment\src\lib\locale'
  using description file: C:\Users\jcomp\git\servoy_master\servoy-eclipse\com.servoy.eclipse.ngclient.ui\node\node_modules\moment\package.json (relative path: ./src/lib/locale)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: C:\Users\jcomp\git\servoy_master\servoy-eclipse\com.servoy.eclipse.ngclient.ui\node\node_modules\moment\package.json (relative path: ./src/lib/locale/locale)
      as directory
        C:\Users\jcomp\git\servoy_master\servoy-eclipse\com.servoy.eclipse.ngclient.ui\node\node_modules\moment\src\lib\locale\locale doesn't exist

but now if i hack a bit that code to do the samething again as before (with that dirname):

localePath = (typeof __dirname !== 'undefined' ? __dirname : '.') + '/locale/' + name;

the problem i get is then;

Warning: ./node_modules/moment/src/lib/locale/locales.js 76:6-32
Critical dependency: the request of a dependency is an expression
    at CommonJsRequireContextDependency.getWarnings (C:\Users\jcomp\git\servoy_master\servoy-eclipse\com.servoy.eclipse.ngclient.ui\node\node_modules\webpack\lib\dependencies\ContextDependency.js:40:18)
    at Compilation.reportDependencyErrorsAndWarnings (C:\Users\jcomp\git\servoy_master\servoy-eclipse\com.servoy.eclipse.ngclient.ui\node\node_modules\webpack\lib\Compilation.js:1454:24)
    at C:\Users\jcomp\git\servoy_master\servoy-eclipse\com.servoy.eclipse.ngclient.ui\node\node_modules\webpack\lib\Compilation.js:1258:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\jcomp\git\servoy_master\servoy-eclipse\com.servoy.eclipse.ngclient.ui\node\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:42:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\jcomp\git\servoy_master\servoy-eclipse\com.servoy.eclipse.ngclient.ui\node\node_modules\tapable\lib\Hook.js:154:20)
    at Compilation.finish (C:\Users\jcomp\git\servoy_master\servoy-eclipse\com.servoy.eclipse.ngclient.ui\node\node_modules\webpack\lib\Compilation.js:1253:28)
    at C:\Users\jcomp\git\servoy_master\servoy-eclipse\com.servoy.eclipse.ngclient.ui\node\node_modules\webpack\lib\Compiler.js:672:17
    at _done (eval at create (C:\Users\jcomp\git\servoy_master\servoy-eclipse\com.servoy.eclipse.ngclient.ui\node\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at eval (eval at create (C:\Users\jcomp\git\servoy_master\servoy-eclipse\com.servoy.eclipse.ngclient.ui\node\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:72:22)
    at C:\Users\jcomp\git\servoy_master\servoy-eclipse\com.servoy.eclipse.ngclient.ui\node\node_modules\webpack\lib\Compilation.js:1185:12
    at C:\Users\jcomp\git\servoy_master\servoy-eclipse\com.servoy.eclipse.ngclient.ui\node\node_modules\webpack\lib\Compilation.js:1097:9
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
 @ ./node_modules/moment/src/lib/locale/locale.js

i use directly the source because i want to use it as a angular es6 module that dynamically loads in the language files
This is working fine by the way, i only get the above errors when building..

so in angular i do:

    return import(`../../node_modules/moment/src/locale/${localeId}`).then(
            module => {  // code }

to really cherry pick only the things i need (so only the locale that is given is loaded)

as far as i see i can only do that through src...

**Comment by jcompagner** [comment]
oh it could be that moment did fix the "es6" support because now i can do this:

        return import(`moment/locale/${localeId}`).then(
            module => {

so i don't need to use src anymore but directly the module itself

Then there are no errors.
