### ISSUE TITLE
add years dont work how expected

### ISSUE THREAD

**Issue by fwilly** [moment/moment#5983]
**Describe the bug**
If I add a year or 12 month the result is unexpected 11 month.

**To Reproduce**
```
let contractDate = new Date('Mon Jan 31 2022 01:00:00 GMT+0100 (Mitteleuropäische Normalzeit)');
console.log(contractDate);
// Mon Jan 31 2022 01:00:00 GMT+0100 (Mitteleuropäische Normalzeit)
let validTo = moment(contractDate).clone();
console.log(validTo.isValid());
// true
console.log(validTo.toString());
// Mon Jan 31 2022 01:00:00 GMT+0100

validTo.add(1, 'year');
console.log(validTo.toString());
// Sat Dec 31 2022 00:00:00 GMT+0100
```

**Expected behavior**
`// Tue Jan 31 2023 01:00:00 GMT+0100`

**Desktop (please complete the following information):**
 - OS: windows 10 64bit
 - node: v14.17.0
 - npm: v6.14.13

**Environment**
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)
Sat Mar 12 2022 20:35:20 GMT+0100 (Mitteleuropäische Normalzeit)
12.3.2022, 20:35:20
-60
ReferenceError: navigator is not defined
    at eval (eval at module.exports (xxx\handler.js:29:29), <anonymous>:4:13)
    at module.exports (xxx\handler.js:29:29)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
2.29.1
```

**Additional context**
The same result I have if I use:
`validTo.add(1, 'years');` or
`validTo.add(12, 'months');`

is peculiar too, that the time is set from `01:00:00` to `00:00:00` by using add().

And if I use `console.log(validTo.get('year'))` in the 5th row I get
```
2021
```

**Comment by fwilly** [comment]
```
let validTo = moment(contract.validTo).clone();
console.log(validTo.toString());
validTo.add(validTo.clone().endOf('year').dayOfYear(), 'days');
console.log(validTo.toString());
```
bring also
```
Mon Jan 31 2022 01:00:00 GMT+0100
Sat Dec 31 2022 00:00:00 GMT+0100
```

Interesting is following:
```
let validTo = moment(contract.validTo).clone();
console.log(validTo.toString());
for (let m=1; m<=12; m++) {
    validTo.add(1, 'month');
    console.log(validTo.toString());
}
```
brings
```
Mon Jan 31 2022 01:00:00 GMT+0100
Mon Jan 31 2022 00:00:00 GMT+0100
Mon Feb 28 2022 00:00:00 GMT+0100
Mon Mar 28 2022 00:00:00 GMT+0200
Thu Apr 28 2022 00:00:00 GMT+0200
Sat May 28 2022 00:00:00 GMT+0200
Tue Jun 28 2022 00:00:00 GMT+0200
Thu Jul 28 2022 00:00:00 GMT+0200
Sun Aug 28 2022 00:00:00 GMT+0200
Wed Sep 28 2022 00:00:00 GMT+0200
Fri Oct 28 2022 00:00:00 GMT+0200
Mon Nov 28 2022 00:00:00 GMT+0100
Wed Dec 28 2022 00:00:00 GMT+0100
```
the first add of 1 month dont do add 1 month. Is set only the hours to 0.

**Comment by fwilly** [comment]
I'm so stupid. I have found my error. Before I add a year I had checked
```
if (date.isAfter(validTo.startOf('month').subtract(1, 'day'))) {
}
```
This has changed `validTo` before. After I changed it to
```
if (date.isAfter(validTo.clone().startOf('month').subtract(1, 'day'))) {
}
```
is works correctly.
