### ISSUE TITLE
When I want to test the momentjs with locale in Jest it throws error.

### ISSUE THREAD

**Issue by arslanalidev** [moment/moment#6049]
**Describe the bug**
I want to use the i18n in my application. I had to implement the moment js locale in react application. But when we run the tests it throws this error. 

```
Summary of all failing tests
 FAIL  src/components/TodayBoostMyLearning/LiveGroupsWidget/LiveGroupsWidget.test.js
  ● Test suite failed to run

    TypeError: moment.defineLocale is not a function

      13 | import laptopImage from './images/laptop.png';
      14 | import moment from 'moment';
    > 15 | import 'moment/min/locales';
         | ^
      16 |
      17 | import LiveGroupImage from './images/LiveGroupsWidget.svg';
      18 | import LiveGroupLaptopImage from './images/laptop.png';

      at factory (node_modules/moment/min/locales.js:10:12)
      at node_modules/moment/min/locales.js:3:43
      at Object.<anonymous> (node_modules/moment/min/locales.js:1:3)
      at Object.<anonymous> (src/components/TodayBoostMyLearning/LiveGroupsWidget/LiveGroupsWidget.js:15:1)
      at Object.<anonymous> (src/components/TodayBoostMyLearning/LiveGroupsWidget/index.js:1:1)
      at Object.<anonymous> (src/components/TodayBoostMyLearning/LiveGroupsWidget/LiveGroupsWidget.test.js:4:1)
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome
 - Version 105

**Moment-specific environment**

* The time zone setting of the machine the code is running on GMT+5:00
* The time and date at which the code was run September 23
* Other libraries in use (TypeScript, Immutable.js, etc) 

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString()): Fri Sep 23 2022 18:09:45 GMT+0500 (Pakistan Standard Time)
console.log((new Date()).toLocaleString()): 9/23/2022, 6:10:07 PM
console.log((new Date()).getTimezoneOffset()): -300
console.log(navigator.userAgent): Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
console.log(moment.version): ^2.29.2
```

**Comment by vladimirevstratov** [comment]
Same problem

**Comment by waiz3ple** [comment]
I'm just facing the same problem right now. I have spent ton of hrs on it

**Comment by mattjohnsonpint** [comment]
Thanks for the report, and sorry this cost several people time! `moment/min/locales` is a generated browser bundle and is not the best Jest entry point. I'd import Moment and only the needed locale modules: `import moment from 'moment'; import 'moment/locale/fr';`. I'd also check that no Jest mock replaces Moment with an object lacking `defineLocale`.
