### ISSUE TITLE
Need an error if parsing format string does not match expected format, instead of giving some default output.

### ISSUE THREAD

**Issue by deepeshpakhare** [moment/moment#6274]
**Is your feature request related to a problem? Please describe.**
In a project's code I was working on, I found that a former developer had mistakenly passed the parsing format string as "dd-MM-YYYY" instead of "DD-MM-YYYY" to moment.js method to parse the date string. Instead of giving an error to the developer while parsing, due to error in parsing format string, the moment.js was putting the day in the date as 01 of that particular month. The dates are critical and showing some default value even with a problematic parsing format is something I found bad.

**Describe the solution you'd like**
Instead of giving output as a default value the moment.js should throw an error related to parsing. 

**Describe alternatives you've considered**
No alternatives considered yet.

**Additional context**
The code line causing above described problem was, moment(this.objHeader.sIssueDate, "dd-MM-yyyy").

**Comment by yanhuacuo** [comment]
```
INFO  Files loaded in 3.4 s
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments:
[0] _isAMomentObject: true, _isUTC: true, _useUTC: true, _l: undefined, _i: 2025-01-02 15:161, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (C:\Users\pc\Documents\blog\cppxiaozhu\node_modules\moment\moment.js:324:25)
    at configFromString (C:\Users\pc\Documents\blog\cppxiaozhu\node_modules\moment\moment.js:2613:19)
    at configFromInput (C:\Users\pc\Documents\blog\cppxiaozhu\node_modules\moment\moment.js:3056:13)
    at prepareConfig (C:\Users\pc\Documents\blog\cppxiaozhu\node_modules\moment\moment.js:3039:13)
    at createFromConfig (C:\Users\pc\Documents\blog\cppxiaozhu\node_modules\moment\moment.js:3006:44)
    at createLocalOrUTC (C:\Users\pc\Documents\blog\cppxiaozhu\node_modules\moment\moment.js:3102:16)
    at Function.createUTC [as utc] (C:\Users\pc\Documents\blog\cppxiaozhu\node_modules\moment\moment.js:106:16)
    at C:\Users\pc\Documents\blog\cppxiaozhu\themes\butterfly\scripts\helpers\page.js:128:28
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\Users\pc\Documents\blog\cppxiaozhu\themes\butterfly\scripts\helpers\page.js:127:15)
    at eval (eval at wrap (C:\Users\pc\Documents\blog\cppxiaozhu\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:1877:15)
    at eval (eval at wrap (C:\Users\pc\Documents\blog\cppxiaozhu\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:2031:4)
    at template (eval at wrap (C:\Users\pc\Documents\blog\cppxiaozhu\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:6799:7)
    at _View._compiled (C:\Users\pc\Documents\blog\cppxiaozhu\node_modules\hexo\dist\theme\view.js:120:67)
    at _View.render (C:\Users\pc\Documents\blog\cppxiaozhu\node_modules\hexo\dist\theme\view.js:37:21)
    at C:\Users\pc\Documents\blog\cppxiaozhu\node_modules\hexo\dist\hexo\index.js:60:29
    at tryCatcher (C:\Users\pc\Documents\blog\cppxiaozhu\node_modules\bluebird\js\release\util.js:16:23)
    at C:\Users\pc\Documents\blog\cppxiaozhu\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (C:\Users\pc\Documents\blog\cppxiaozhu\node_modules\hexo\dist\hexo\router.js:43:9)
    at Readable.read (node:internal/streams/readable:739:12)
    at resume_ (node:internal/streams/readable:1257:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```
