### ISSUE TITLE
Documentation incorrect: lang().months returns function rather than months array

### ISSUE THREAD

**Issue by JasonCust** [moment/moment#682]
Documentation states:

``` javascript
var fr = moment().lang('fr');
fr.lang().months // ["janvier", "février", "mars", ...]
```

but on a Node.js REPL:

``` javascript
var fr = moment().lang('fr');
fr.lang().months // [Function]
```

Side note: executing the function throws an error

``` javascript
fr.lang().months()
TypeError: Cannot call method 'month' of undefined
    at Object.Language.months (./node_modules/moment/moment.js:352:35)
    at repl:1:12
    at REPLServer.self.eval (repl.js:109:21)
    at Interface.<anonymous> (repl.js:248:12)
    at Interface.EventEmitter.emit (events.js:96:17)
    at Interface._onLine (readline.js:200:10)
    at Interface._line (readline.js:518:8)
    at Interface._ttyWrite (readline.js:736:14)
    at ReadStream.onkeypress (readline.js:97:10)
    at ReadStream.EventEmitter.emit (events.js:126:20)
    at emitKey (readline.js:1058:12)
    at ReadStream.onData (readline.js:807:7)
```

**Comment by mikegleasonjr** [comment]
2 years later and the doc is still wrong...
